### ISSUE TITLE
Watch options for changes

### ISSUE THREAD

**Issue by offsky** [jtblin/angular-chart.js#47]
There are a lot of "options" that can be passed through to Chart.js. It would be nice if these were dynamic so that if we changed an option the chart would automatically update. You can accomplish this by watching the "options" databinding in angular-chart. Here is how I did it:

```
scope.$watch('options', function (newVal, oldVal) {
          var chartType = type || scope.chartType;
          if (! chartType) return;
          if (chart) chart.destroy();
          chart = createChart(chartType, scope, elem);
});
```

You could also do it with this line, but then you would have to modify the first line of resetChart to allow an object to pass through.
```
scope.$watch('options', resetChart, true);
```

**Comment by jtblin** [comment]
Thank you for the suggestion, I prefer going with your second option and modify `resertChart` to support objects in order to avoid code duplication. I'll go ahead and implement that.

**Comment by jtblin** [comment]
Done, published in 0.3.20.

**Comment by shaifulborhan** [comment]
Hi,

May I know what is the correct way to code this properly? I have a chart that can be toggled from pie to bar and vice-versa. Basically when viewing bar chart, I would like to customize the scales a little bit. I managed to do this on first load but I am not able to change the options on the fly. When I switched back to pie chart, the scale is still present although I tried to modify the scope var for the options to disable scales.

Please advise.

**Comment by jtblin** [comment]
Just change the options...
